// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: active_energy_entries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listActiveEnergyEntries = `-- name: ListActiveEnergyEntries :many
SELECT id, user_id, day, active_energy_kcal, source, created_at, updated_at FROM active_energy_entries
WHERE user_id = $1
  AND ($2::date IS NULL OR day >= $2)
  AND ($3::date IS NULL OR day <= $3)
ORDER BY day ASC
`

type ListActiveEnergyEntriesParams struct {
	UserID pgtype.UUID `json:"user_id"`
	From   pgtype.Date `json:"from"`
	To     pgtype.Date `json:"to"`
}

func (q *Queries) ListActiveEnergyEntries(ctx context.Context, arg ListActiveEnergyEntriesParams) ([]ActiveEnergyEntry, error) {
	rows, err := q.db.Query(ctx, listActiveEnergyEntries, arg.UserID, arg.From, arg.To)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveEnergyEntry
	for rows.Next() {
		var i ActiveEnergyEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Day,
			&i.ActiveEnergyKcal,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertActiveEnergyByDay = `-- name: UpsertActiveEnergyByDay :one
INSERT INTO active_energy_entries (user_id, day, active_energy_kcal, source)
VALUES ($1, $2, $3, 'google')
ON CONFLICT (user_id, day)
DO UPDATE SET active_energy_kcal = excluded.active_energy_kcal, updated_at = now()
RETURNING id, user_id, day, active_energy_kcal, source, created_at, updated_at
`

type UpsertActiveEnergyByDayParams struct {
	UserID           pgtype.UUID    `json:"user_id"`
	Day              pgtype.Date    `json:"day"`
	ActiveEnergyKcal pgtype.Numeric `json:"active_energy_kcal"`
}

func (q *Queries) UpsertActiveEnergyByDay(ctx context.Context, arg UpsertActiveEnergyByDayParams) (ActiveEnergyEntry, error) {
	row := q.db.QueryRow(ctx, upsertActiveEnergyByDay, arg.UserID, arg.Day, arg.ActiveEnergyKcal)
	var i ActiveEnergyEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Day,
		&i.ActiveEnergyKcal,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
