// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: allowed_users.sql

package db

import (
	"context"
)

const deleteAllowedUserByEmail = `-- name: DeleteAllowedUserByEmail :exec
DELETE FROM allowed_users WHERE email = $1
`

func (q *Queries) DeleteAllowedUserByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteAllowedUserByEmail, email)
	return err
}

const isEmailAllowed = `-- name: IsEmailAllowed :one
SELECT EXISTS (
    SELECT 1 FROM allowed_users WHERE email = $1
) AS allowed
`

func (q *Queries) IsEmailAllowed(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, isEmailAllowed, email)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const listAllowedEmails = `-- name: ListAllowedEmails :many
SELECT email FROM allowed_users ORDER BY email
`

func (q *Queries) ListAllowedEmails(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAllowedEmails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAllowedUser = `-- name: UpsertAllowedUser :exec
INSERT INTO allowed_users (email) VALUES ($1)
ON CONFLICT (email) DO NOTHING
`

func (q *Queries) UpsertAllowedUser(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, upsertAllowedUser, email)
	return err
}
