// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: google_oauth_credentials.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGoogleOAuthCredentials = `-- name: DeleteGoogleOAuthCredentials :exec
DELETE FROM google_oauth_credentials WHERE user_id = $1
`

func (q *Queries) DeleteGoogleOAuthCredentials(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGoogleOAuthCredentials, userID)
	return err
}

const getGoogleOAuthCredentialsByUserID = `-- name: GetGoogleOAuthCredentialsByUserID :one
SELECT id, user_id, google_health_user_id, refresh_token_encrypted, refresh_token_nonce, access_token_encrypted, access_token_nonce, access_token_expires_at, connected_at, updated_at FROM google_oauth_credentials WHERE user_id = $1
`

func (q *Queries) GetGoogleOAuthCredentialsByUserID(ctx context.Context, userID pgtype.UUID) (GoogleOauthCredential, error) {
	row := q.db.QueryRow(ctx, getGoogleOAuthCredentialsByUserID, userID)
	var i GoogleOauthCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoogleHealthUserID,
		&i.RefreshTokenEncrypted,
		&i.RefreshTokenNonce,
		&i.AccessTokenEncrypted,
		&i.AccessTokenNonce,
		&i.AccessTokenExpiresAt,
		&i.ConnectedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGoogleOAuthCredentials = `-- name: UpsertGoogleOAuthCredentials :one
INSERT INTO google_oauth_credentials (
    user_id, google_health_user_id,
    refresh_token_encrypted, refresh_token_nonce,
    access_token_encrypted, access_token_nonce, access_token_expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id) DO UPDATE SET
    google_health_user_id = excluded.google_health_user_id,
    refresh_token_encrypted = excluded.refresh_token_encrypted,
    refresh_token_nonce = excluded.refresh_token_nonce,
    access_token_encrypted = excluded.access_token_encrypted,
    access_token_nonce = excluded.access_token_nonce,
    access_token_expires_at = excluded.access_token_expires_at,
    updated_at = now()
RETURNING id, user_id, google_health_user_id, refresh_token_encrypted, refresh_token_nonce, access_token_encrypted, access_token_nonce, access_token_expires_at, connected_at, updated_at
`

type UpsertGoogleOAuthCredentialsParams struct {
	UserID                pgtype.UUID        `json:"user_id"`
	GoogleHealthUserID    string             `json:"google_health_user_id"`
	RefreshTokenEncrypted []byte             `json:"refresh_token_encrypted"`
	RefreshTokenNonce     []byte             `json:"refresh_token_nonce"`
	AccessTokenEncrypted  []byte             `json:"access_token_encrypted"`
	AccessTokenNonce      []byte             `json:"access_token_nonce"`
	AccessTokenExpiresAt  pgtype.Timestamptz `json:"access_token_expires_at"`
}

func (q *Queries) UpsertGoogleOAuthCredentials(ctx context.Context, arg UpsertGoogleOAuthCredentialsParams) (GoogleOauthCredential, error) {
	row := q.db.QueryRow(ctx, upsertGoogleOAuthCredentials,
		arg.UserID,
		arg.GoogleHealthUserID,
		arg.RefreshTokenEncrypted,
		arg.RefreshTokenNonce,
		arg.AccessTokenEncrypted,
		arg.AccessTokenNonce,
		arg.AccessTokenExpiresAt,
	)
	var i GoogleOauthCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoogleHealthUserID,
		&i.RefreshTokenEncrypted,
		&i.RefreshTokenNonce,
		&i.AccessTokenEncrypted,
		&i.AccessTokenNonce,
		&i.AccessTokenExpiresAt,
		&i.ConnectedAt,
		&i.UpdatedAt,
	)
	return i, err
}
