// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: height_entries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestHeightEntry = `-- name: GetLatestHeightEntry :one
SELECT id, user_id, height_cm, recorded_at, source, google_data_point_id, created_at FROM height_entries
WHERE user_id = $1
ORDER BY recorded_at DESC
LIMIT 1
`

func (q *Queries) GetLatestHeightEntry(ctx context.Context, userID pgtype.UUID) (HeightEntry, error) {
	row := q.db.QueryRow(ctx, getLatestHeightEntry, userID)
	var i HeightEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HeightCm,
		&i.RecordedAt,
		&i.Source,
		&i.GoogleDataPointID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertHeightEntryByGoogleID = `-- name: UpsertHeightEntryByGoogleID :one
INSERT INTO height_entries (user_id, height_cm, recorded_at, source, google_data_point_id)
VALUES ($1, $2, $3, 'google', $4)
ON CONFLICT (user_id, google_data_point_id) WHERE google_data_point_id IS NOT NULL
DO UPDATE SET height_cm = excluded.height_cm, recorded_at = excluded.recorded_at
RETURNING id, user_id, height_cm, recorded_at, source, google_data_point_id, created_at
`

type UpsertHeightEntryByGoogleIDParams struct {
	UserID            pgtype.UUID        `json:"user_id"`
	HeightCm          pgtype.Numeric     `json:"height_cm"`
	RecordedAt        pgtype.Timestamptz `json:"recorded_at"`
	GoogleDataPointID *string            `json:"google_data_point_id"`
}

func (q *Queries) UpsertHeightEntryByGoogleID(ctx context.Context, arg UpsertHeightEntryByGoogleIDParams) (HeightEntry, error) {
	row := q.db.QueryRow(ctx, upsertHeightEntryByGoogleID,
		arg.UserID,
		arg.HeightCm,
		arg.RecordedAt,
		arg.GoogleDataPointID,
	)
	var i HeightEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HeightCm,
		&i.RecordedAt,
		&i.Source,
		&i.GoogleDataPointID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertHeightEntryByRecordedAt = `-- name: UpsertHeightEntryByRecordedAt :one
INSERT INTO height_entries (user_id, height_cm, recorded_at, source, google_data_point_id)
VALUES ($1, $2, $3, 'google', NULL)
ON CONFLICT (user_id, recorded_at) WHERE source = 'google' AND google_data_point_id IS NULL
DO UPDATE SET height_cm = excluded.height_cm
RETURNING id, user_id, height_cm, recorded_at, source, google_data_point_id, created_at
`

type UpsertHeightEntryByRecordedAtParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	HeightCm   pgtype.Numeric     `json:"height_cm"`
	RecordedAt pgtype.Timestamptz `json:"recorded_at"`
}

func (q *Queries) UpsertHeightEntryByRecordedAt(ctx context.Context, arg UpsertHeightEntryByRecordedAtParams) (HeightEntry, error) {
	row := q.db.QueryRow(ctx, upsertHeightEntryByRecordedAt, arg.UserID, arg.HeightCm, arg.RecordedAt)
	var i HeightEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HeightCm,
		&i.RecordedAt,
		&i.Source,
		&i.GoogleDataPointID,
		&i.CreatedAt,
	)
	return i, err
}
