// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: magic_link_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentMagicLinkTokensForEmail = `-- name: CountRecentMagicLinkTokensForEmail :one
SELECT count(*) FROM magic_link_tokens
WHERE user_email = $1
  AND created_at > now() - interval '1 hour'
`

func (q *Queries) CountRecentMagicLinkTokensForEmail(ctx context.Context, userEmail string) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentMagicLinkTokensForEmail, userEmail)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMagicLinkToken = `-- name: CreateMagicLinkToken :one
INSERT INTO magic_link_tokens (user_email, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_email, token_hash, expires_at, used_at, created_at
`

type CreateMagicLinkTokenParams struct {
	UserEmail string             `json:"user_email"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateMagicLinkToken(ctx context.Context, arg CreateMagicLinkTokenParams) (MagicLinkToken, error) {
	row := q.db.QueryRow(ctx, createMagicLinkToken, arg.UserEmail, arg.TokenHash, arg.ExpiresAt)
	var i MagicLinkToken
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getValidMagicLinkToken = `-- name: GetValidMagicLinkToken :one
SELECT id, user_email, token_hash, expires_at, used_at, created_at FROM magic_link_tokens
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetValidMagicLinkToken(ctx context.Context, tokenHash string) (MagicLinkToken, error) {
	row := q.db.QueryRow(ctx, getValidMagicLinkToken, tokenHash)
	var i MagicLinkToken
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markMagicLinkTokenUsed = `-- name: MarkMagicLinkTokenUsed :exec
UPDATE magic_link_tokens SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkMagicLinkTokenUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markMagicLinkTokenUsed, id)
	return err
}
