// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: overwhelm_tags.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveOverwhelmTag = `-- name: ArchiveOverwhelmTag :execrows
UPDATE overwhelm_tags
SET archived_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2 AND archived_at IS NULL
`

type ArchiveOverwhelmTagParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) ArchiveOverwhelmTag(ctx context.Context, arg ArchiveOverwhelmTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveOverwhelmTag, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createOrUnarchiveOverwhelmTag = `-- name: CreateOrUnarchiveOverwhelmTag :one
INSERT INTO overwhelm_tags (user_id, name)
VALUES ($1, $2)
ON CONFLICT (user_id, lower(name))
DO UPDATE SET name = excluded.name, archived_at = NULL, updated_at = now()
RETURNING id, user_id, name, archived_at, created_at, updated_at
`

type CreateOrUnarchiveOverwhelmTagParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

func (q *Queries) CreateOrUnarchiveOverwhelmTag(ctx context.Context, arg CreateOrUnarchiveOverwhelmTagParams) (OverwhelmTag, error) {
	row := q.db.QueryRow(ctx, createOrUnarchiveOverwhelmTag, arg.UserID, arg.Name)
	var i OverwhelmTag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOverwhelmTags = `-- name: ListOverwhelmTags :many
SELECT id, user_id, name, archived_at, created_at, updated_at FROM overwhelm_tags
WHERE user_id = $1 AND archived_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListOverwhelmTags(ctx context.Context, userID pgtype.UUID) ([]OverwhelmTag, error) {
	rows, err := q.db.Query(ctx, listOverwhelmTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OverwhelmTag
	for rows.Next() {
		var i OverwhelmTag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameOverwhelmTag = `-- name: RenameOverwhelmTag :one
UPDATE overwhelm_tags
SET name = $3, updated_at = now()
WHERE id = $1 AND user_id = $2 AND archived_at IS NULL
RETURNING id, user_id, name, archived_at, created_at, updated_at
`

type RenameOverwhelmTagParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

func (q *Queries) RenameOverwhelmTag(ctx context.Context, arg RenameOverwhelmTagParams) (OverwhelmTag, error) {
	row := q.db.QueryRow(ctx, renameOverwhelmTag, arg.ID, arg.UserID, arg.Name)
	var i OverwhelmTag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
