// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: overwhelm_entries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listOverwhelmEntries = `-- name: ListOverwhelmEntries :many
SELECT id, user_id, day, overwhelm_level, created_at, updated_at FROM overwhelm_entries
WHERE user_id = $1
  AND ($2::date IS NULL OR day >= $2)
  AND ($3::date IS NULL OR day <= $3)
ORDER BY day ASC
`

type ListOverwhelmEntriesParams struct {
	UserID pgtype.UUID `json:"user_id"`
	From   pgtype.Date `json:"from"`
	To     pgtype.Date `json:"to"`
}

func (q *Queries) ListOverwhelmEntries(ctx context.Context, arg ListOverwhelmEntriesParams) ([]OverwhelmEntry, error) {
	rows, err := q.db.Query(ctx, listOverwhelmEntries, arg.UserID, arg.From, arg.To)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OverwhelmEntry
	for rows.Next() {
		var i OverwhelmEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Day,
			&i.OverwhelmLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOverwhelmByDay = `-- name: UpsertOverwhelmByDay :one
INSERT INTO overwhelm_entries (user_id, day, overwhelm_level)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, day)
DO UPDATE SET overwhelm_level = excluded.overwhelm_level, updated_at = now()
RETURNING id, user_id, day, overwhelm_level, created_at, updated_at
`

type UpsertOverwhelmByDayParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	Day            pgtype.Date `json:"day"`
	OverwhelmLevel int16       `json:"overwhelm_level"`
}

func (q *Queries) UpsertOverwhelmByDay(ctx context.Context, arg UpsertOverwhelmByDayParams) (OverwhelmEntry, error) {
	row := q.db.QueryRow(ctx, upsertOverwhelmByDay, arg.UserID, arg.Day, arg.OverwhelmLevel)
	var i OverwhelmEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Day,
		&i.OverwhelmLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
