// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountRecentMagicLinkTokensForEmail(ctx context.Context, userEmail string) (int64, error)
	CreateMagicLinkToken(ctx context.Context, arg CreateMagicLinkTokenParams) (MagicLinkToken, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, email string) (User, error)
	DeleteAllowedUserByEmail(ctx context.Context, email string) error
	DeleteGoogleOAuthCredentials(ctx context.Context, userID pgtype.UUID) error
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	GetGoogleOAuthCredentialsByUserID(ctx context.Context, userID pgtype.UUID) (GoogleOauthCredential, error)
	GetSession(ctx context.Context, id pgtype.UUID) (Session, error)
	GetSyncMetadataByUserID(ctx context.Context, userID pgtype.UUID) (SyncMetadatum, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetValidMagicLinkToken(ctx context.Context, tokenHash string) (MagicLinkToken, error)
	IsEmailAllowed(ctx context.Context, email string) (bool, error)
	ListAllowedEmails(ctx context.Context) ([]string, error)
	MarkMagicLinkTokenUsed(ctx context.Context, id pgtype.UUID) error
	UpdateLastLoginAt(ctx context.Context, id pgtype.UUID) error
	UpdateSyncWatermarks(ctx context.Context, arg UpdateSyncWatermarksParams) error
	UpsertAllowedUser(ctx context.Context, email string) error
	UpsertGoogleOAuthCredentials(ctx context.Context, arg UpsertGoogleOAuthCredentialsParams) (GoogleOauthCredential, error)
	UpsertHeightEntryByGoogleID(ctx context.Context, arg UpsertHeightEntryByGoogleIDParams) (HeightEntry, error)
	UpsertHeightEntryByRecordedAt(ctx context.Context, arg UpsertHeightEntryByRecordedAtParams) (HeightEntry, error)
	UpsertSyncMetadata(ctx context.Context, userID pgtype.UUID) (SyncMetadatum, error)
	UpsertWeightEntryByGoogleID(ctx context.Context, arg UpsertWeightEntryByGoogleIDParams) (WeightEntry, error)
	UpsertWeightEntryByRecordedAt(ctx context.Context, arg UpsertWeightEntryByRecordedAtParams) (WeightEntry, error)
}

var _ Querier = (*Queries)(nil)
