// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountRecentMagicLinkTokensForEmail(ctx context.Context, userEmail string) (int64, error)
	CreateMagicLinkToken(ctx context.Context, arg CreateMagicLinkTokenParams) (MagicLinkToken, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, email string) (User, error)
	DeleteAllowedUserByEmail(ctx context.Context, email string) error
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	GetSession(ctx context.Context, id pgtype.UUID) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetValidMagicLinkToken(ctx context.Context, tokenHash string) (MagicLinkToken, error)
	IsEmailAllowed(ctx context.Context, email string) (bool, error)
	ListAllowedEmails(ctx context.Context) ([]string, error)
	MarkMagicLinkTokenUsed(ctx context.Context, id pgtype.UUID) error
	UpdateLastLoginAt(ctx context.Context, id pgtype.UUID) error
	UpsertAllowedUser(ctx context.Context, email string) error
}

var _ Querier = (*Queries)(nil)
