// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountRecentMagicLinkTokensForEmail(ctx context.Context, userEmail string) (int64, error)
	CreateMagicLinkToken(ctx context.Context, arg CreateMagicLinkTokenParams) (MagicLinkToken, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, email string) (User, error)
	CreateWeightEntry(ctx context.Context, arg CreateWeightEntryParams) (WeightEntry, error)
	DeleteAllowedUserByEmail(ctx context.Context, email string) error
	DeleteGoogleOAuthCredentials(ctx context.Context, userID pgtype.UUID) error
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	DeleteWeightEntry(ctx context.Context, arg DeleteWeightEntryParams) (int64, error)
	ExistsHeightEntryForDate(ctx context.Context, arg ExistsHeightEntryForDateParams) (bool, error)
	ExistsWeightEntryForDate(ctx context.Context, arg ExistsWeightEntryForDateParams) (bool, error)
	GetGoogleOAuthCredentialsByUserID(ctx context.Context, userID pgtype.UUID) (GoogleOauthCredential, error)
	GetLatestHeightEntry(ctx context.Context, userID pgtype.UUID) (HeightEntry, error)
	GetLatestWeightEntry(ctx context.Context, userID pgtype.UUID) (WeightEntry, error)
	GetSession(ctx context.Context, id pgtype.UUID) (Session, error)
	GetSyncMetadataByUserID(ctx context.Context, userID pgtype.UUID) (SyncMetadatum, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetValidMagicLinkToken(ctx context.Context, tokenHash string) (MagicLinkToken, error)
	GetWeightEntryByID(ctx context.Context, arg GetWeightEntryByIDParams) (WeightEntry, error)
	IsEmailAllowed(ctx context.Context, email string) (bool, error)
	ListActiveEnergyEntries(ctx context.Context, arg ListActiveEnergyEntriesParams) ([]ActiveEnergyEntry, error)
	ListAllowedEmails(ctx context.Context) ([]string, error)
	ListUnsyncedManualWeightEntries(ctx context.Context, userID pgtype.UUID) ([]WeightEntry, error)
	ListWeightEntries(ctx context.Context, arg ListWeightEntriesParams) ([]WeightEntry, error)
	MarkMagicLinkTokenUsed(ctx context.Context, id pgtype.UUID) error
	UpdateLastLoginAt(ctx context.Context, id pgtype.UUID) error
	UpdateSyncWatermarks(ctx context.Context, arg UpdateSyncWatermarksParams) error
	UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (User, error)
	UpdateWeightEntry(ctx context.Context, arg UpdateWeightEntryParams) (WeightEntry, error)
	UpdateWeightEntryGoogleSync(ctx context.Context, arg UpdateWeightEntryGoogleSyncParams) (WeightEntry, error)
	UpsertActiveEnergyByDay(ctx context.Context, arg UpsertActiveEnergyByDayParams) (ActiveEnergyEntry, error)
	UpsertAllowedUser(ctx context.Context, email string) error
	UpsertGoogleOAuthCredentials(ctx context.Context, arg UpsertGoogleOAuthCredentialsParams) (GoogleOauthCredential, error)
	UpsertHeightEntryByGoogleID(ctx context.Context, arg UpsertHeightEntryByGoogleIDParams) (HeightEntry, error)
	UpsertHeightEntryByRecordedAt(ctx context.Context, arg UpsertHeightEntryByRecordedAtParams) (HeightEntry, error)
	UpsertSyncMetadata(ctx context.Context, userID pgtype.UUID) (SyncMetadatum, error)
	UpsertWeightEntryByGoogleID(ctx context.Context, arg UpsertWeightEntryByGoogleIDParams) (WeightEntry, error)
	UpsertWeightEntryByRecordedAt(ctx context.Context, arg UpsertWeightEntryByRecordedAtParams) (WeightEntry, error)
}

var _ Querier = (*Queries)(nil)
