// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_metadata.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSyncMetadataByUserID = `-- name: GetSyncMetadataByUserID :one
SELECT id, user_id, last_full_backfill_at, last_incremental_sync_at, weight_sync_watermark, height_sync_watermark, updated_at, active_energy_sync_watermark FROM sync_metadata WHERE user_id = $1
`

func (q *Queries) GetSyncMetadataByUserID(ctx context.Context, userID pgtype.UUID) (SyncMetadatum, error) {
	row := q.db.QueryRow(ctx, getSyncMetadataByUserID, userID)
	var i SyncMetadatum
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LastFullBackfillAt,
		&i.LastIncrementalSyncAt,
		&i.WeightSyncWatermark,
		&i.HeightSyncWatermark,
		&i.UpdatedAt,
		&i.ActiveEnergySyncWatermark,
	)
	return i, err
}

const updateSyncWatermarks = `-- name: UpdateSyncWatermarks :exec
UPDATE sync_metadata SET
    last_full_backfill_at = $2,
    last_incremental_sync_at = $3,
    weight_sync_watermark = $4,
    height_sync_watermark = $5,
    active_energy_sync_watermark = $6,
    updated_at = now()
WHERE user_id = $1
`

type UpdateSyncWatermarksParams struct {
	UserID                    pgtype.UUID        `json:"user_id"`
	LastFullBackfillAt        pgtype.Timestamptz `json:"last_full_backfill_at"`
	LastIncrementalSyncAt     pgtype.Timestamptz `json:"last_incremental_sync_at"`
	WeightSyncWatermark       pgtype.Timestamptz `json:"weight_sync_watermark"`
	HeightSyncWatermark       pgtype.Timestamptz `json:"height_sync_watermark"`
	ActiveEnergySyncWatermark pgtype.Timestamptz `json:"active_energy_sync_watermark"`
}

func (q *Queries) UpdateSyncWatermarks(ctx context.Context, arg UpdateSyncWatermarksParams) error {
	_, err := q.db.Exec(ctx, updateSyncWatermarks,
		arg.UserID,
		arg.LastFullBackfillAt,
		arg.LastIncrementalSyncAt,
		arg.WeightSyncWatermark,
		arg.HeightSyncWatermark,
		arg.ActiveEnergySyncWatermark,
	)
	return err
}

const upsertSyncMetadata = `-- name: UpsertSyncMetadata :one
INSERT INTO sync_metadata (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET user_id = excluded.user_id
RETURNING id, user_id, last_full_backfill_at, last_incremental_sync_at, weight_sync_watermark, height_sync_watermark, updated_at, active_energy_sync_watermark
`

func (q *Queries) UpsertSyncMetadata(ctx context.Context, userID pgtype.UUID) (SyncMetadatum, error) {
	row := q.db.QueryRow(ctx, upsertSyncMetadata, userID)
	var i SyncMetadatum
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LastFullBackfillAt,
		&i.LastIncrementalSyncAt,
		&i.WeightSyncWatermark,
		&i.HeightSyncWatermark,
		&i.UpdatedAt,
		&i.ActiveEnergySyncWatermark,
	)
	return i, err
}
