// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email)
VALUES ($1)
RETURNING id, email, manual_height_cm, units_preference, created_at, last_login_at
`

func (q *Queries) CreateUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ManualHeightCm,
		&i.UnitsPreference,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, manual_height_cm, units_preference, created_at, last_login_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ManualHeightCm,
		&i.UnitsPreference,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, manual_height_cm, units_preference, created_at, last_login_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ManualHeightCm,
		&i.UnitsPreference,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const updateLastLoginAt = `-- name: UpdateLastLoginAt :exec
UPDATE users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) UpdateLastLoginAt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLoginAt, id)
	return err
}
