// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: weight_entries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertWeightEntryByGoogleID = `-- name: UpsertWeightEntryByGoogleID :one
INSERT INTO weight_entries (user_id, weight_kg, recorded_at, source, google_data_point_id)
VALUES ($1, $2, $3, 'google', $4)
ON CONFLICT (user_id, google_data_point_id) WHERE google_data_point_id IS NOT NULL
DO UPDATE SET weight_kg = excluded.weight_kg, recorded_at = excluded.recorded_at, updated_at = now()
RETURNING id, user_id, weight_kg, recorded_at, bmi, height_used_cm, source, google_data_point_id, google_sync_status, created_at, updated_at
`

type UpsertWeightEntryByGoogleIDParams struct {
	UserID            pgtype.UUID        `json:"user_id"`
	WeightKg          pgtype.Numeric     `json:"weight_kg"`
	RecordedAt        pgtype.Timestamptz `json:"recorded_at"`
	GoogleDataPointID *string            `json:"google_data_point_id"`
}

func (q *Queries) UpsertWeightEntryByGoogleID(ctx context.Context, arg UpsertWeightEntryByGoogleIDParams) (WeightEntry, error) {
	row := q.db.QueryRow(ctx, upsertWeightEntryByGoogleID,
		arg.UserID,
		arg.WeightKg,
		arg.RecordedAt,
		arg.GoogleDataPointID,
	)
	var i WeightEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeightKg,
		&i.RecordedAt,
		&i.Bmi,
		&i.HeightUsedCm,
		&i.Source,
		&i.GoogleDataPointID,
		&i.GoogleSyncStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWeightEntryByRecordedAt = `-- name: UpsertWeightEntryByRecordedAt :one
INSERT INTO weight_entries (user_id, weight_kg, recorded_at, source, google_data_point_id)
VALUES ($1, $2, $3, 'google', NULL)
ON CONFLICT (user_id, recorded_at) WHERE source = 'google' AND google_data_point_id IS NULL
DO UPDATE SET weight_kg = excluded.weight_kg, updated_at = now()
RETURNING id, user_id, weight_kg, recorded_at, bmi, height_used_cm, source, google_data_point_id, google_sync_status, created_at, updated_at
`

type UpsertWeightEntryByRecordedAtParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	WeightKg   pgtype.Numeric     `json:"weight_kg"`
	RecordedAt pgtype.Timestamptz `json:"recorded_at"`
}

func (q *Queries) UpsertWeightEntryByRecordedAt(ctx context.Context, arg UpsertWeightEntryByRecordedAtParams) (WeightEntry, error) {
	row := q.db.QueryRow(ctx, upsertWeightEntryByRecordedAt, arg.UserID, arg.WeightKg, arg.RecordedAt)
	var i WeightEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeightKg,
		&i.RecordedAt,
		&i.Bmi,
		&i.HeightUsedCm,
		&i.Source,
		&i.GoogleDataPointID,
		&i.GoogleSyncStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
